---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  vars:
   token_bot: "{{ lookup('env','token_bot') }}"
   DATABASE_URL: "{{ lookup('env','DATABASE_URL')}}"
   redis_port: 6379
  pre_tasks:
  - name: Instalar python
    become: yes
    raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python-minimal)
  tasks:
    - name: actualizar update
      apt: name=apt state=latest
    - name: Instalar build-essential y tcl8.5
      apt: name=build-essential state=present
      apt: name=tcl8.5 state=present
    - name: Instalar make
      apt: name=make state=present
    - name: Instalar wget
      apt: name=wget state=present
    - name: Instalar gcc
      apt: name=gcc state=present
    - name: Instalar y ejecutar rabbitmq
      shell: echo "deb http://www.rabbitmq.com/debian/ testing main" >> /etc/apt/sources.list
      shell: curl http://www.rabbitmq.com/rabbitmq-signing-key-public.asc | apt-key add -
    - name: Instalar rabbitmq
      apt: name=apt state=latest
      apt: name=rabbitmq-server state=present
    - name: Añadir usuario
      command: rabbitmqctl add_user invitado invitado
    - name: Dar permisos
      command: rabbitmqctl set_permissions invitado ".*" ".*" ".*"
    - name: activar interfaz grafica
      command: rabbitmq-plugins enable rabbitmq_management
    - name: Descargar redis
      command: wget http://download.redis.io/redis-stable.tar.gz
    - name: Descomprimir redis
      command: tar xzf redis-stable.tar.gz
    - name: jmelloc
      command: make distclean -C ./redis-stable
    - name: Ejecutar make
      command: make -C ./redis-stable
    #- name: Ejecutar test
    #  shell: make test -C ./redis-stable
    - name: Instalar
      command: make install -C ./redis-stable
    - name: Crear carpeta
      command: mkdir /etc/redis
    - name: Ejecutar .sh
      command: ./redis-stable/utils/install_server.sh
    - name: copiar redis.conf file
      command: cp /vagrant/conf_redis/6379.conf /etc/redis


    - name: cleaning up build files
      command: rm -rf ./{{ item }}
      with_items:
        - redis-stable
        - redis-stable.tar.gz
