language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - easy_install pip
  - pip install virtualenv 
install:
  - pip install -r requirements.txt
script:
  - python manage.py migrate
  - python manage.py test
